package config

const (
	PROTOCOL    = "PROTOCOL"
	MYSQLURL    = "MYSQL_URL"
	REDISURL    = "REDIS_URL"
	LISTENADDR  = "ADDR"
	CERTFILE    = "CERT_FILE"
	KEYFILE     = "KEY_FILE"
	DEBUG       = "DEBUG"
	URL         = "API_URL"
	NAVERKEY    = "NAVER_KEY"
	NAVERSECRET = "NAVER_SECRET"
	JWTSECRET   = "JWT_SECRET"
)
