-- MySQL Script generated by MySQL Workbench
-- 2018년 05월 24일 (목) 오후 04시 37분 11초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gorani_reader
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gorani_reader
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gorani_reader` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `gorani_reader` ;

-- -----------------------------------------------------
-- Table `gorani_reader`.`word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`word` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(45) NOT NULL,
  `word_pronunciation` VARCHAR(45) NULL,
  PRIMARY KEY (`word_id`),
  UNIQUE INDEX `uq_word_idx` (`word` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`relevant_word_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`relevant_word_type` (
  `relevant_word_type_code` INT NOT NULL,
  `relevant_word_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`relevant_word_type_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`relevant_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`relevant_word` (
  `word_id` INT NOT NULL,
  `target_word_id` INT NOT NULL,
  `relevant_word_sequence` INT NOT NULL,
  `relevant_word_type_code` INT NOT NULL,
  PRIMARY KEY (`word_id`, `target_word_id`, `relevant_word_sequence`),
  INDEX `fk_relevant_word2_idx` (`target_word_id` ASC),
  INDEX `fk_relevant_word3_idx` (`relevant_word_type_code` ASC),
  CONSTRAINT `fk_relevant_word`
    FOREIGN KEY (`word_id`)
    REFERENCES `gorani_reader`.`word` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relevant_word2`
    FOREIGN KEY (`target_word_id`)
    REFERENCES `gorani_reader`.`word` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relevant_word3`
    FOREIGN KEY (`relevant_word_type_code`)
    REFERENCES `gorani_reader`.`relevant_word_type` (`relevant_word_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`sentence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`sentence` (
  `sentence_id` INT NOT NULL AUTO_INCREMENT,
  `sentence` VARCHAR(100) NULL,
  `book_id` INT NULL,
  PRIMARY KEY (`sentence_id`),
  INDEX `fk_sentence_idx` (`book_id` ASC),
  CONSTRAINT `fk_sentence`
    FOREIGN KEY (`book_id`)
    REFERENCES `gorani_reader`.`book` (`book_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`word_sentence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`word_sentence` (
  `word_id` INT NOT NULL,
  `sentence_id` INT NOT NULL,
  PRIMARY KEY (`word_id`, `sentence_id`),
  INDEX `fk_word_sentence2_idx` (`sentence_id` ASC),
  CONSTRAINT `fk_word_sentence2`
    FOREIGN KEY (`sentence_id`)
    REFERENCES `gorani_reader`.`sentence` (`sentence_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word_sentence`
    FOREIGN KEY (`word_id`)
    REFERENCES `gorani_reader`.`word` (`word_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`definition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`definition` (
  `definition_id` INT NOT NULL AUTO_INCREMENT,
  `word_id` INT NOT NULL,
  `definition_pos` VARCHAR(45) NULL,
  `definition` VARCHAR(100) NULL,
  PRIMARY KEY (`definition_id`),
  CONSTRAINT `fk_definition`
    FOREIGN KEY (`word_id`)
    REFERENCES `gorani_reader`.`word` (`word_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`known_word`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`known_word` (
  `user_id` INT NOT NULL,
  `word_id` INT NOT NULL,
  `known_word_added_date` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `word_id`),
  INDEX `fk_known_word2_idx` (`word_id` ASC),
  CONSTRAINT `fk_known_word`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorani_reader`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_known_word2`
    FOREIGN KEY (`word_id`)
    REFERENCES `gorani_reader`.`word` (`word_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`user_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`user_detail` (
  `user_id` INT NOT NULL,
  `user_profile_image` BLOB NULL,
  `user_added_date` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_detail`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorani_reader`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`oauth_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`oauth_service` (
  `oauth_service_code` INT NOT NULL,
  `oauth_service_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oauth_service_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`oauth_passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`oauth_passport` (
  `user_id` INT NOT NULL,
  `oauth_service_code` INT NOT NULL,
  `oauth_user_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`, `oauth_service_code`),
  INDEX `fk_oauth_passport2_idx` (`oauth_service_code` ASC),
  CONSTRAINT `fk_oauth_passport2`
    FOREIGN KEY (`oauth_service_code`)
    REFERENCES `gorani_reader`.`oauth_service` (`oauth_service_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oauth_passport`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorani_reader`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`book_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`book_detail` (
  `book_id` INT NOT NULL,
  `book_cover_image` BLOB NULL,
  `book_author` VARCHAR(45) NULL,
  `book_popularity` VARCHAR(45) NULL,
  `book_publish_date` DATE NULL,
  PRIMARY KEY (`book_id`),
  CONSTRAINT `fk_book_detail`
    FOREIGN KEY (`book_id`)
    REFERENCES `gorani_reader`.`book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`wordbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`wordbook` (
  `wordbook_uuid` BINARY(16) NOT NULL,
  `user_id` INT NOT NULL,
  `wordbook_is_unknown` BIT(1) NOT NULL,
  `wordbook_name` VARCHAR(45) NULL,
  `wordbook_update_date` DATETIME NOT NULL,
  PRIMARY KEY (`wordbook_uuid`),
  INDEX `fk_wordbook_idx` (`user_id` ASC),
  CONSTRAINT `fk_wordbook`
    FOREIGN KEY (`user_id`)
    REFERENCES `gorani_reader`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`wordbook_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`wordbook_entry` (
  `wordbook_uuid` BINARY(16) NOT NULL,
  `definition_id` INT NOT NULL,
  `wordbook_entry_source_book` VARCHAR(45) NULL,
  `wordbook_entry_source_sentence` VARCHAR(100) NULL,
  `wordbook_entry_update_date` DATETIME NOT NULL,
  PRIMARY KEY (`definition_id`, `wordbook_uuid`),
  INDEX `fk_wordbook_entry2_idx` (`definition_id` ASC),
  CONSTRAINT `fk_wordbook_entry`
    FOREIGN KEY (`wordbook_uuid`)
    REFERENCES `gorani_reader`.`wordbook` (`wordbook_uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wordbook_entry2`
    FOREIGN KEY (`definition_id`)
    REFERENCES `gorani_reader`.`definition` (`definition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`wordbook_quiz_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`wordbook_quiz_type` (
  `wordbook_quiz_type_code` INT NOT NULL,
  `wordbook_quiz_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`wordbook_quiz_type_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`wordbook_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`wordbook_quiz` (
  `wordbook_uuid` BINARY(16) NOT NULL,
  `wordbook_quiz_time` INT NOT NULL,
  `wordbook_quiz_type_code` INT NOT NULL,
  `wordbook_quiz_accuracy` DOUBLE NOT NULL,
  `wordbook_quiz_ended_date` DATETIME NOT NULL,
  PRIMARY KEY (`wordbook_uuid`, `wordbook_quiz_time`, `wordbook_quiz_type_code`),
  INDEX `fk_wordbook_quiz2_idx` (`wordbook_quiz_type_code` ASC),
  CONSTRAINT `fk_wordbook_quiz`
    FOREIGN KEY (`wordbook_uuid`)
    REFERENCES `gorani_reader`.`wordbook` (`wordbook_uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wordbook_quiz2`
    FOREIGN KEY (`wordbook_quiz_type_code`)
    REFERENCES `gorani_reader`.`wordbook_quiz_type` (`wordbook_quiz_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gorani_reader`.`wordbook_quiz_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`wordbook_quiz_entry` (
  `wordbook_uuid` BINARY(16) NOT NULL,
  `wordbook_quiz_time` INT NOT NULL,
  `definition_id` INT NOT NULL,
  `wordbook_quiz_entry_correct` DOUBLE NOT NULL,
  PRIMARY KEY (`wordbook_uuid`, `definition_id`, `wordbook_quiz_time`),
  INDEX `fk_wordbook_quiz_entry_idx` (`wordbook_uuid` ASC, `wordbook_quiz_time` ASC),
  INDEX `fk_wordbook_quiz_entry2_idx` (`definition_id` ASC),
  CONSTRAINT `fk_wordbook_quiz_entry`
    FOREIGN KEY (`wordbook_uuid` , `wordbook_quiz_time`)
    REFERENCES `gorani_reader`.`wordbook_quiz` (`wordbook_uuid` , `wordbook_quiz_time`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wordbook_quiz_entry2`
    FOREIGN KEY (`definition_id`)
    REFERENCES `gorani_reader`.`definition` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gorani_reader` ;

-- -----------------------------------------------------
-- Placeholder table for view `gorani_reader`.`user_with_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`user_with_detail` (`user_id` INT, `user_name` INT, `user_profile_image` INT, `user_added_date` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gorani_reader`.`oauth_passport_by_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gorani_reader`.`oauth_passport_by_service` (`oauth_service_name` INT, `oauth_user_id` INT, `user_id` INT);

-- -----------------------------------------------------
-- View `gorani_reader`.`user_with_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorani_reader`.`user_with_detail`;
USE `gorani_reader`;
CREATE  OR REPLACE VIEW `user_with_detail` AS
SELECT
	u.user_id,
    u.user_name,
    ud.user_profile_image,
    ud.user_added_date
from user u, user_detail ud
WHERE u.user_id = ud.user_id;

-- -----------------------------------------------------
-- View `gorani_reader`.`oauth_passport_by_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gorani_reader`.`oauth_passport_by_service`;
USE `gorani_reader`;
CREATE  OR REPLACE VIEW `oauth_passport_by_service` AS
SELECT
	os.oauth_service_name,
    op.oauth_user_id,
    op.user_id
from oauth_passport op, oauth_service os
where op.oauth_service_code = os.oauth_service_code;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
